In [1]:
from tensorflow.keras.utils import to_categorical
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

%matplotlib inline
import tensorflow as tf

import os

2025-11-22 12:10:29.819039: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-11-22 12:10:29.855470: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-11-22 12:10:29.855507: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-11-22 12:10:29.856547: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-11-22 12:10:29.862203: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-11-22 12:10:29.862755: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [2]:
import hls4ml
from tensorflow.keras.models import load_model
from tensorflow.keras.utils import plot_model

model = load_model('qkeras/lstm/model_toptag_lstm.h5')

config = hls4ml.utils.config_from_keras_model(model, granularity='model', default_precision='ap_fixed<16,6>')

hls_model = hls4ml.converters.convert_from_keras_model(
    model, hls_config=config, output_dir='model_lstm_hls/hls4ml_prj', part='xc7vx690tffg1761-2'
)

In [ ]:
import numpy as np
data = np.load("x_test.npy")
print(data[:10])
with open("dump_test.txt") as f:
    f.write(data)
del data

[[[0.15952477 0.42420992 0.50315732 0.15588839 0.01821551 0.5250904 ]
  [0.13198355 0.42420992 0.43044853 0.13066565 0.02555556 0.52938515]
  [0.12084481 0.42497075 0.49941784 0.11810011 0.01584965 0.52938515]
  ...
  [0.0156805  0.4412905  0.54676777 0.01547626 0.04780645 0.52938515]
  [0.01535458 0.43856126 0.56600744 0.01520126 0.0574013  0.52938515]
  [0.01446368 0.4253757  0.43808022 0.01427509 0.02083896 0.45230561]]

 [[0.1456919  0.54083353 0.50353497 0.14205389 0.01038125 0.42744124]
  [0.11625119 0.53881377 0.50854582 0.11259349 0.01483665 0.45230561]
  [0.09565384 0.54125571 0.50504684 0.092994   0.01155035 0.45230561]
  ...
  [0.01709076 0.53962451 0.5203715  0.01622619 0.02394556 0.54769439]
  [0.01625695 0.54091954 0.50153744 0.01590346 0.00878054 0.5250904 ]
  [0.01513878 0.55287933 0.51443756 0.01435395 0.02482832 0.5250904 ]]

 [[0.17414805 0.54083353 0.50353497 0.17127869 0.01942318 0.52938515]
  [0.16710414 0.54111326 0.50229079 0.16445091 0.01839453 0.57255876]
  [0

In [9]:
import h5py

#Open the H5 file in read mode
with h5py.File('val/jetImage_7_30p_0_10000.h5', 'r') as file:
    # print(&quot;Keys: %s&quot; % file.keys())
    # a_group_key = list(file.keys())[0]
    print(list(file.keys()))
    print(len(list(file.keys())))
    for key in file.keys():
        print(key)
        print(len(list(file[key][:10])))
        print(list(file[key][:10]))
    # Getting the data
    # data = list(file[a_group_key])
    # print(data)

['jetConstituentList', 'jetFeatureNames', 'jetImage', 'jetImageECAL', 'jetImageHCAL', 'jets', 'particleFeatureNames']
7
jetConstituentList
10
[array([[ 8.50040131e+01,  1.61570282e+01, -3.22926788e+01,
         9.23556671e+01,  8.68296325e-02,  8.65259018e+01,
         8.79576355e-02, -3.65051836e-01,  2.46186834e-02,
        -0.00000000e+00,  1.87833086e-01, -7.81396404e-02,
         0.00000000e+00,  8.19260851e-02, -3.49656045e-01,
         6.12323426e-17],
       [ 6.89332428e+01,  2.53270817e+01, -2.84522858e+01,
         7.87578964e+01,  7.40454718e-02,  7.34387741e+01,
         7.46539533e-02, -3.78338009e-01,  1.13325231e-02,
        -3.68082741e-15,  3.52103949e-01,  8.61312225e-02,
        -1.64802417e-01,  8.68735462e-02, -3.61263245e-01,
        -3.71352585e-15],
       [ 5.46207657e+01,  1.97999458e+01, -2.37680759e+01,
         6.27797012e+01,  5.90233244e-02,  5.80987587e+01,
         5.90601116e-02, -3.98469120e-01, -8.79860297e-03,
        -2.04089675e-02,  3.47765654e-

In [3]:
hls4ml.utils.plot_model(hls_model, show_shapes=True, show_precision=True, to_file="toptagging_lstm_layers.png")
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (LSTM)               (None, 20)                2160      
                                                                 
 layer3 (Dense)              (None, 64)                1344      
                                                                 
 output_sigmoid (Dense)      (None, 1)                 65        
                                                                 
Total params: 3569 (13.94 KB)
Trainable params: 3569 (13.94 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [4]:
hls_model.compile()

In [6]:
os.environ["XILINX_VIVADO"] = "/tools/Disk_Xilinx/Vivado/2019.1"
os.environ["XILINXD_LICENSE_FILE"] = "2100@xilinxd.xilinx-dev"
os.environ["PATH"] = "/tools/Disk_Xilinx/Vivado/2019.1/bin:" + os.environ.get("PATH", "")
hls_model.build(csim=False, synth=True, vsynth=True)


****** Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
  **** IP Build 2548770 on Fri May 24 18:01:18 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

source /tools/Disk_Xilinx/Vivado/2019.1/scripts/vivado_hls/hls.tcl -notrace
INFO: [HLS 200-10] Running '/tools/Disk_Xilinx/Vivado/2019.1/bin/unwrapped/lnx64.o/vivado_hls'
INFO: [HLS 200-10] For user 'leo' on host 'hvm1' (Linux_x86_64 version 5.15.0-161-generic) on Sat Nov 22 12:10:56 PST 2025
INFO: [HLS 200-10] On os Ubuntu 22.04.5 LTS
INFO: [HLS 200-10] In directory '/home/leo/HLS4ML_VS_MANUAL/documents/Benchmarks/Toptag/model_lstm_hls/hls4ml_prj'
Sourcing Tcl script 'build_prj.tcl'
INFO: [HLS 200-10] Creating and opening project '/home/leo/HLS4ML_VS_MANUAL/documents/Benchmarks/Toptag/model_lstm_hls/hls4ml_prj/myproject_prj'.
INFO: [HLS 200-10] Adding design file 'firmware/myproject.cpp' to the project
INFO: [HLS 200-10] Adding 

{'CSynthesisReport': {'TargetClockPeriod': '5.00',
  'EstimatedClockPeriod': '4.890',
  'BestLatency': '353',
  'WorstLatency': '353',
  'IntervalMin': '354',
  'IntervalMax': '354',
  'BRAM_18K': '41',
  'DSP': '2498',
  'FF': '76158',
  'LUT': '116669',
  'URAM': '0',
  'AvailableBRAM_18K': '2940',
  'AvailableDSP': '3600',
  'AvailableFF': '866400',
  'AvailableLUT': '433200',
  'AvailableURAM': '0'},
 'VivadoSynthReport': {'LUT': '59224',
  'FF': '37062',
  'BRAM_18K': '20.5',
  'DSP48E': '2489'}}

In [7]:
hls4ml.report.read_vivado_report('model_lstm_hls/hls4ml_prj')

Found 1 solution(s) in model_lstm_hls/hls4ml_prj/myproject_prj.
Reports for solution "solution1":

C simulation report not found.
SYNTHESIS REPORT:
== Vivado HLS Report for 'myproject'
* Date:           Sat Nov 22 12:20:48 2025

* Version:        2019.1 (Build 2552052 on Fri May 24 15:28:33 MDT 2019)
* Project:        myproject_prj
* Solution:       solution1
* Product family: virtex7
* Target device:  xc7vx690t-ffg1761-2


== Performance Estimates
+ Timing (ns): 
    * Summary: 
    +--------+-------+----------+------------+
    |  Clock | Target| Estimated| Uncertainty|
    +--------+-------+----------+------------+
    |ap_clk  |   5.00|     4.890|        0.62|
    +--------+-------+----------+------------+

+ Latency (clock cycles): 
    * Summary: 
    +-----+-----+-----+-----+---------+
    |  Latency  |  Interval | Pipeline|
    | min | max | min | max |   Type  |
    +-----+-----+-----+-----+---------+
    |  353|  353|  353|  353|   none  |
    +-----+-----+-----+-----+-------