In [6]:
import tensorflow as tf
import numpy as np
from qkeras.utils import _add_supported_quantized_objects

FILE_PATH = '/home/aya/HLS4ML_VS_MANUAL/src/hdl/RHEED_Gaussian/Models/gaussian_nov24.keras'

def dice_loss(y_true, y_pred, delta=0.5):

    weights = tf.constant([3.0, 1.0, 2.0, 2.0, 0.1], dtype=tf.float32)
    y_pred = y_pred + 1e-8
    diff = y_true - y_pred
    abs_diff = tf.abs(diff)

    quadratic = tf.minimum(abs_diff, delta)
    linear = abs_diff - quadratic
    huber_loss = 0.5 * tf.square(quadratic) + delta * linear

    weighted_loss = weights * huber_loss
    return tf.reduce_mean(weighted_loss)
    
co = {}
_add_supported_quantized_objects(co)
# Add any custom losses
co["dice_loss"] = dice_loss

model = tf.keras.models.load_model(FILE_PATH, custom_objects=co)
model.summary()

2026-09-15 08:25:54.200829: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-09-15 08:25:54.414302: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/aya/local_libs:
2026-09-15 08:25:54.414346: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2026-09-15 08:25:55.409143: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared obje

Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089


Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089


Model: "pp_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 q_conv2d_batchnorm (QConv2D  (None, 46, 46, 6)        85        
 Batchnorm)                                                      
                                                                 
 q_activation (QActivation)  (None, 46, 46, 6)         0         
                                                                 
 max_pooling2d (MaxPooling2D  (None, 11, 11, 6)        0         
 )                                                               
                                                                 
 q_conv2d_batchnorm_1 (QConv  (None, 9, 9, 8)          473       
 2DBatchnorm)                                                    
                                                                 
 q_activation_1 (QActivation  (None, 9, 9, 8)          0         
 )                                                        

In [7]:
layer = model.get_layer("q_conv2d_batchnorm")


# weights = layer.get_folded_weights() # batchnorm params already folded into conv weights
# weights = layer.get_weights()

# print([w.shape for w in layer.get_folded_weights()])
# print([w.shape for w in layer.get_weights()])

for layer in model.layers:
    if "conv" in layer.name:
        print([w.shape for w in layer.get_folded_weights()])
    else:
        print([w.shape for w in layer.get_weights()])
# print(weights)

# weights are float32 at this point
# fused_weights, fused_bias = layer.get_folded_weights()
# print(fused_weights)
# print(fused_bias)
for layer in model.layers:
    if 'conv2d_batchnorm' in layer.name.lower():
        fused_weights, fused_bias = layer.get_folded_weights()
        w_max = np.abs(fused_weights).max()
        b_max = np.abs(fused_bias).max()
    elif 'dense' in layer.name.lower():
        weights = layer.get_weights()
        if len(weights) == 0:
            continue
        kernel, bias = weights[0], weights[1]
        w_max = np.abs(kernel).max()
        b_max = np.abs(bias).max()
    else:
        # MaxPool, Flatten, QActivation, etc. — no weights to check
        continue

    print(f"{layer.name}: weight_max={w_max:.4f}, bias_max={b_max:.4f}")


[TensorShape([3, 3, 1, 6]), TensorShape([6])]
[]
[]
[TensorShape([3, 3, 6, 8]), TensorShape([8])]
[]
[]
[TensorShape([3, 3, 8, 10]), TensorShape([10])]
[]
[]
[]
[(10, 15), (15,)]
[]
[(15, 10), (10,)]
[]
[(10, 5), (5,)]
q_conv2d_batchnorm: weight_max=0.5807, bias_max=1.0622
q_conv2d_batchnorm_1: weight_max=0.6640, bias_max=0.1900
q_conv2d_batchnorm_2: weight_max=0.9269, bias_max=0.6406
q_dense: weight_max=1.1430, bias_max=0.3326
q_dense_1: weight_max=0.8786, bias_max=0.2050
q_dense_2: weight_max=0.9524, bias_max=1.0174


In [8]:
import numpy as np
import math
import os

# Rounding half up matches Xilinx's AP_RND rounding convention (different from np.round())
def round_half_up(x):
    return math.floor(x + 0.5) if x >= 0 else math.ceil(x - 0.5)

def dec_to_bin(number : int | float, bits=-1):
    """
    Converts a decimal number to a str binary representation
    
    :param number: Number to convert into binary
    :type number: int | float
    :param bits: Bitwidth of output number. If negative, uses the minimum amount
    """
    # Determines if a number is negative
    neg=False
    if (number<0):
        number*=-1
        number-=1
        neg=True
    
    # Rounds number up to nearest int
    number=int(round_half_up(number)) # instead of np.round()
    out=""

    # Return maximum positive or negative number if the input cannot be represented by the bitwidth
    if (bits>0 and neg==False and number>2**(bits-1)-1):
        return "0" + "1"*(bits-1)
    elif (bits>0 and neg==True and number>=2**(bits-1)):
        return "1" + "0"*(bits-1)
    
    # Do typical conversion of decimal to binary number
    while (number>0):
        res = number%2
        if (neg):
            res= 0 if (res==1) else 1
        out=f"{res}{out}"
        if (len(out)==(bits-1)):
            break
        number=int(number/2)
        
    # Add signed bit
    if (neg):
        out=f"{1}{out}"
    else: out=f"{0}{out}"

    # If the number was 0
    if (len(out)==0):
        out="0"

    # Sign extension
    while (len(out)<bits):
        out=f"{out[0]}{out}"

    return out

In [4]:
def gen_weight(accuracy, model, target_dir="./"):
    """
    Generate weight and bias packages from keras model
    :param accuracy: Accuracy for packages. Formatted (width, integers)
    :type accuracy: (int, int)

    """
    # The start of each number
    head = f"{accuracy[0]}'b"

    Nfrac = accuracy[0] - accuracy[1] - 1 # assuming accuracy[1] does NOT include the sign bit
    # The amount of weights for each layer
    current = 0
    for layer in model.layers:
        if 'conv2d_batchnorm' in layer.name.lower():
            # fused_weights shape: 4Darray (height, width, inputChannels, outputChannels)
            # fused_bias: 1D array
            fused_weights, fused_bias = layer.get_folded_weights()
            # transpose to match sv indexing in conv2d module: (o, i, h, w)
            fused_weights_t = np.transpose(fused_weights,(3, 2, 0, 1))
            # flatten
            fused_weights_f = fused_weights_t.reshape(-1)
            contents = [fused_weights_f, fused_bias]
            # debug
            print(type(fused_weights_f))
            print(fused_weights_f.shape)
            print(type(fused_weights_f[0]))
            print(fused_weights_f[0].shape)
        else:
            contents = layer.get_weights()

        # need to also check if layer.get_weights() returns empty list and skip (maxpool)
        if (contents!=None and len(contents) > 0): # for dense layers
            # contents = np.concatenate((contents, np.zeros(len(contents[1]))), axis=1)
            if 'conv2d_batchnorm' in layer.name.lower():
                weights = [fused_weights_f]
                biases  = [fused_bias]
            else:
                weights = []
                biases = []
                for cont in contents:
                    try:
                        len(cont[0])
                        weights.append(cont)
                    except:
                        biases.append(cont)
                if (len(weights)!=len(biases)):
                    print(len(weights), len(biases))
                    biases.append(np.zeros_like(biases[0]))
            for i in range(len(weights)):
                name = layer.name
                # Converting the files to arrays
                weight = weights[i]
                bias = biases[i]

                # Output file name
                filename = os.path.join(target_dir, f"{name}_pkg_{accuracy[0]}_{accuracy[1]}_{i}.sv")
                # if (not os.path.isfile(filename)):
                with open(filename, "w") as f:
                    # Writes the header to the file
                    f.write("`timescale 1ns / 1ps\n")
                    f.write(f"//Width: {accuracy[0]}\n//Int: {accuracy[1]}\n")
                    f.write(f"package {name}_{i}_{accuracy[0]}_{accuracy[1]};\n\n")

                    ### NEW for 2d convolution ### (since weights are now flattened instead of 2d like dense)
                    if 'conv2d_batchnorm' in name.lower():
                        f.write(f"localparam logic signed [{accuracy[0]-1}:0] convWeights [0:{len(weight)-1}] = '" + "{\n")

                        # Writes the main body of the function
                        for i in range(len(weight)):
                            # f.write("{")
                            num = dec_to_bin(weight[i]*(2**(Nfrac)), accuracy[0])
                            f.write(f"{head}{num}")
                            if (i!=len(weight)-1): 
                                f.write(",\n")
                        f.write("};\n")
                        f.write(f"localparam logic signed [{accuracy[0]-1}:0] convBiases [{len(bias)}] = '"+"{\n")
                        for i in range(0, len(bias)):
                            num = dec_to_bin(bias[i]*(2**Nfrac), accuracy[0])
                            f.write(f"{head}{num}")
                            f.write(",\n" if i!=(len(bias)-1) else "\n};\nendpackage")
                    #############################
                    # else:
                    #     f.write(f"localparam logic signed [{accuracy[0]-1}:0] weights [{len(weight)}][{len(weight[0])}] = '" + "{\n")

                    #     # Writes the main body of the function
                    #     for i in range(len(weight)):
                    #         f.write("{")
                    #         num = dec_to_bin(weight[i][0]*(2**(Nfrac)), accuracy[0])
                    #         f.write(f"{head}{num}")
                    #         for j in range(1, len(weight[0])):
                    #             num = dec_to_bin(weight[i][j]*(2**(Nfrac)), accuracy[0])
                    #             f.write(f", {head}{num}")
                    #         if (i!=len(weight)-1): 
                    #             f.write("},\n")
                    #     f.write("}\n};\n")
                    #                                                             # len(weights[0]) happens to be len(bias) for dense layers
                    #     f.write(f"localparam logic signed [{accuracy[0]-1}:0] bias [{len(weight[0])}] = '"+"{\n")
                    #     for i in range(0, len(bias)):
                    #         num = dec_to_bin(bias[i]*(2**Nfrac), accuracy[0])
                    #         f.write(f"{head}{num}")
                    #         f.write(",\n" if i!=(len(bias)-1) else "\n};\nendpackage")
                    
                    #############################
                    else:
                        # Flatten the (INPUT_SIZE, OUTPUT_SIZE) kernel row-major, i.e.
                        # flat_index = input_idx * OUTPUT_SIZE + output_idx.
                        # This matches sumOneColumnParameterized's indexing:
                        #   dlWeights[y*OUTPUT_SIZE + ITER]  where y = input index, ITER = output index
                        weight_flat = weight.reshape(-1)
 
                        f.write(f"localparam logic signed [{accuracy[0]-1}:0] dlWeights [0:{len(weight_flat)-1}] = '" + "{\n")
 
                        # Writes the main body of the function
                        for k in range(len(weight_flat)):
                            num = dec_to_bin(weight_flat[k]*(2**(Nfrac)), accuracy[0])
                            f.write(f"{head}{num}")
                            if (k!=len(weight_flat)-1):
                                f.write(",\n")
                        f.write("\n};\n")
 
                        # bias stays 1D, one entry per output neuron (length == OUTPUT_SIZE)
                        f.write(f"localparam logic signed [{accuracy[0]-1}:0] bias [{len(bias)}] = '"+"{\n")
                        for i in range(0, len(bias)):
                            num = dec_to_bin(bias[i]*(2**Nfrac), accuracy[0])
                            f.write(f"{head}{num}")
                            f.write(",\n" if i!=(len(bias)-1) else "\n};\nendpackage")

In [16]:
TOTAL_BITS = 8
NUM_INT = 1

gen_weight(accuracy=(TOTAL_BITS, NUM_INT), model=model, target_dir="./")


<class 'numpy.ndarray'>
(54,)
<class 'numpy.float32'>
()
<class 'numpy.ndarray'>
(432,)
<class 'numpy.float32'>
()
<class 'numpy.ndarray'>
(720,)
<class 'numpy.float32'>
()


In [5]:
def gen_conv2d_test_data(accuracy, input_width, num_filters, filt_dimension, target_dir="./"):
    """
    Generate test data package for conv2d_reuse9 testbench
    :param accuracy: Accuracy for packages. Formatted (width, integers)
    :type accuracy: (int, int)

    """
    # The start of each number
    head = f"{accuracy[0]}'b"

    # Nfrac = accuracy[0] - accuracy[1]

    # Generates random weights, biases, and input pixels
    num_weights = num_filters * filt_dimension**2
    # np.random.randint(low, high, size)
    # range of signed two's complement: -2^(n-1) to +2^(n-1)-1
    weights = np.random.randint(-(2**(accuracy[0]-1)), 2**(accuracy[0]-1), num_weights).tolist()
    biases   = np.random.randint(-(2**(accuracy[0]-1)), 2**(accuracy[0]-1), num_filters).tolist()
    pixels  = np.random.randint(-(2**(accuracy[0]-1)), 2**(accuracy[0]-1), input_width**2).tolist()
    
    # Output file name
    filename = os.path.join(target_dir, 
                            f"conv2d_reuse9_test_data_{accuracy[0]}_{accuracy[1]}_{input_width}_{num_filters}_{filt_dimension}.sv")

    with open(filename, "w") as f:
        # Writes the header to the file
        f.write(f"package conv2d_reuse9_test_data;\n")

        # inputMatrix (1D array)
        f.write(f"localparam logic signed [{accuracy[0]-1}:0] inputMatrix [0:{len(pixels)-1}] = '" + "{\n")
        for i in range(len(pixels)):
            # don't need to multiply by 2**Nfrac because randint already gives us integers, not floating point
            num = dec_to_bin(pixels[i], accuracy[0])
            f.write(f"{head}{num}")
            if (i!=len(pixels)-1): 
                f.write(",\n")
        f.write("};\n")
        # convWeights
        f.write(f"localparam logic signed [{accuracy[0]-1}:0] convWeights [0:{len(weights)-1}] = '" + "{\n")
        for i in range(len(weights)):
            num = dec_to_bin(weights[i], accuracy[0])
            f.write(f"{head}{num}")
            if (i!=len(weights)-1): 
                f.write(",\n")
        f.write("};\n")
        # convBiases
        f.write(f"localparam logic signed [{accuracy[0]-1}:0] convBiases [{len(biases)}] = '"+"{\n")
        for i in range(0, len(biases)):
            num = dec_to_bin(biases[i], accuracy[0])
            f.write(f"{head}{num}")
            f.write(",\n" if i!=(len(biases)-1) else "\n};\nendpackage")

In [6]:
def gen_conv2d_multichannel_test_data(accuracy, input_width, num_filters, filt_dimension, input_channels, target_dir="./"):
    """
    Generate test data package for conv2d_reuse9_multichannel testbench
    :param accuracy: Accuracy for packages. Formatted (width, integers)
    :type accuracy: (int, int)

    """
    # The start of each number
    head = f"{accuracy[0]}'b"

    # Generates random weights, biases, and input pixels
    num_weights = num_filters * input_channels * filt_dimension**2
    # np.random.randint(low, high, size)
    # range of signed two's complement: -2^(n-1) to +2^(n-1)-1
    weights = np.random.randint(-(2**(accuracy[0]-1)), 2**(accuracy[0]-1), num_weights).tolist()
    biases   = np.random.randint(-(2**(accuracy[0]-1)), 2**(accuracy[0]-1), num_filters).tolist()
    # pixels now generated per channel: shape [input_channels][input_width**2]
    pixels  = np.random.randint(-(2**(accuracy[0]-1)), 2**(accuracy[0]-1), (input_channels, input_width**2)).tolist()
    
    # Output file name
    filename = os.path.join(target_dir, 
                            f"conv2d_reuse9_multichannel_test_data_{accuracy[0]}_{accuracy[1]}_{input_width}_{num_filters}_{filt_dimension}_{input_channels}.sv")

    with open(filename, "w") as f:
        # Writes the header to the file
        f.write(f"package conv2d_reuse9_multichannel_test_data;\n")

        # inputMatrix (2D array: [channel][pixel])
        f.write(f"localparam logic signed [{accuracy[0]-1}:0] inputMatrix [0:{input_channels-1}][0:{input_width**2-1}] = '" + "{\n")
        for ch in range(input_channels):
            f.write("'{\n")
            for i in range(len(pixels[ch])):
                num = dec_to_bin(pixels[ch][i], accuracy[0])
                f.write(f"{head}{num}")
                if (i != len(pixels[ch])-1):
                    f.write(",\n")
            f.write("}")
            if (ch != input_channels-1):
                f.write(",\n")
            else:
                f.write("\n")
        f.write("};\n")

        # convWeights (still 1D — flattened as (filt*input_channels + ch)*filtDimension**2 + kernel_row*filtDimension + kernel_col)
        f.write(f"localparam logic signed [{accuracy[0]-1}:0] convWeights [0:{len(weights)-1}] = '" + "{\n")
        for i in range(len(weights)):
            num = dec_to_bin(weights[i], accuracy[0])
            f.write(f"{head}{num}")
            if (i!=len(weights)-1): 
                f.write(",\n")
        f.write("};\n")
        # convBiases (unchanged — still one per filter, channel-agnostic)
        f.write(f"localparam logic signed [{accuracy[0]-1}:0] convBiases [{len(biases)}] = '"+"{\n")
        for i in range(0, len(biases)):
            num = dec_to_bin(biases[i], accuracy[0])
            f.write(f"{head}{num}")
            f.write(",\n" if i!=(len(biases)-1) else "\n};\nendpackage")

In [7]:
def gen_dense_test_data(accuracy, input_size, output_size, target_dir="./"):
    """
    Generate test data package for a dense layer testbench
    :param accuracy: Accuracy for packages. Formatted (width, integers)
    :type accuracy: (int, int)

    """
    # The start of each number
    head = f"{accuracy[0]}'b"

    # Generates random weights, biases, and input vector
    num_weights = input_size * output_size
    # np.random.randint(low, high, size)
    # range of signed two's complement: -2^(n-1) to +2^(n-1)-1
    weights = np.random.randint(-(2**(accuracy[0]-1)), 2**(accuracy[0]-1), num_weights).tolist()
    biases  = np.random.randint(-(2**(accuracy[0]-1)), 2**(accuracy[0]-1), output_size).tolist()
    # inputVector: 1D, shape [input_size]
    inputs  = np.random.randint(-(2**(accuracy[0]-1)), 2**(accuracy[0]-1), input_size).tolist()

    # Output file name
    filename = os.path.join(target_dir,
                            f"dense_test_data_{accuracy[0]}_{accuracy[1]}_{input_size}_{output_size}.sv")

    with open(filename, "w") as f:
        # Writes the header to the file
        f.write(f"package dense_test_data;\n")

        # inputVector (1D array: [input_idx])
        # f.write(f"localparam logic signed [{accuracy[0]-1}:0] inputVector [0:{input_size-1}] = '" + "{\n")
        # for i in range(len(inputs)):
        #     num = dec_to_bin(inputs[i], accuracy[0])
        #     f.write(f"{head}{num}")
        #     if (i != len(inputs)-1):
        #         f.write(",\n")
        # f.write("};\n")
        
        f.write(f"localparam logic signed [{accuracy[0]-1}:0] inputVector [{input_size-1}:0] = '" + "{\n")
        for i, val in enumerate(reversed(inputs)):
            num = dec_to_bin(val, accuracy[0])
            f.write(f"{head}{num}")
            if i != len(inputs) - 1:
                f.write(",\n")
        f.write("};\n")

        # dlWeights (1D — flattened as input_idx*OUTPUT_SIZE + output_idx,
        # matching sumOneColumnParameterized's dlWeights[y*OUTPUT_SIZE + ITER] indexing)
        f.write(f"localparam logic signed [{accuracy[0]-1}:0] dlWeights [0:{len(weights)-1}] = '" + "{\n")
        for i in range(len(weights)):
            num = dec_to_bin(weights[i], accuracy[0])
            f.write(f"{head}{num}")
            if (i!=len(weights)-1):
                f.write(",\n")
        f.write("};\n")

        # biases (unchanged — one per output neuron)
        f.write(f"localparam logic signed [{accuracy[0]-1}:0] biases [{len(biases)}] = '"+"{\n")
        for i in range(0, len(biases)):
            num = dec_to_bin(biases[i], accuracy[0])
            f.write(f"{head}{num}")
            f.write(",\n" if i!=(len(biases)-1) else "\n};\nendpackage")

In [ ]:
import numpy as np
import os

TOTAL_BITS = 16
NUM_INT = 6
INPUT_WIDTH = 48
NUM_FILTERS = 6
FILT_DIMENSION = 3

INPUT_CHANNELS = 8

# gen_conv2d_test_data(accuracy=(TOTAL_BITS, NUM_INT), 
#                      input_width=INPUT_WIDTH, 
#                      num_filters=NUM_FILTERS, 
#                      filt_dimension=FILT_DIMENSION, 
#                      target_dir="./")

gen_conv2d_multichannel_test_data(accuracy=(TOTAL_BITS, NUM_INT), 
                     input_width=INPUT_WIDTH, 
                     num_filters=NUM_FILTERS, 
                     filt_dimension=FILT_DIMENSION,
                     input_channels=INPUT_CHANNELS,
                     target_dir="./")

# INPUT_SIZE = 10
# OUTPUT_SIZE = 15
# gen_dense_test_data(accuracy=(TOTAL_BITS, NUM_INT), 
#                      input_size=INPUT_SIZE,
#                      output_size=OUTPUT_SIZE, 
#                      target_dir="./")

In [9]:
with open("/home/aya/HLS4ML_VS_MANUAL/src/hdl/RHEED_Gaussian/python/gaussian_test_data/onehot_0_y0_x0.txt") as f:
    first_line = f.readline().strip()
print("raw bits:", first_line)

pixel_val_int = int(first_line, 2)
if pixel_val_int >= 128:  # convert from unsigned bit pattern to signed
    pixel_val_int -= 256
print("pixel int value (ground truth from file):", pixel_val_int)

raw bits: 01111111
pixel int value (ground truth from file): 127


In [10]:
Nfrac_weight = 6
ch = 0

weight_normal_int = round(float(fused_weights[0, 0, 0, ch]) * (2**Nfrac_weight))
weight_reversed_int = round(float(fused_weights[2, 2, 0, ch]) * (2**Nfrac_weight))
bias_int = round(float(fused_bias[ch]) * (2**Nfrac_weight))

Nfrac_pixel = 7
pixel_val_int = 127

product_normal = (pixel_val_int * weight_normal_int) >> Nfrac_pixel
product_reversed = (pixel_val_int * weight_reversed_int) >> Nfrac_pixel

expected_normal = product_normal + bias_int
expected_reversed = product_reversed + bias_int

print("weight_normal_int (top-left kernel weight):", weight_normal_int)
print("weight_reversed_int (bottom-right kernel weight):", weight_reversed_int)
print("bias_int:", bias_int)
print()
print("Hypothesis A (normal pairing) expected raw output:", expected_normal)
print("Hypothesis B (reversed pairing) expected raw output:", expected_reversed)

weight_normal_int (top-left kernel weight): 8
weight_reversed_int (bottom-right kernel weight): -9
bias_int: -3

Hypothesis A (normal pairing) expected raw output: 4
Hypothesis B (reversed pairing) expected raw output: -12


In [11]:
import numpy as np
rtl_conv0_raw = np.loadtxt("/home/aya/HLS4ML_VS_MANUAL/src/hdl/RHEED_Gaussian/python/round_up_traces/rtl_0_conv0.csv", delimiter=',')
actual_rtl_raw = int(rtl_conv0_raw[0, 0])  # row 0 (first output position), column 0 (channel 0)
print("Actual RTL raw value (position 0, channel 0):", actual_rtl_raw)

Actual RTL raw value (position 0, channel 0): 0


In [12]:
print("Matches Hypothesis A (normal)?", actual_rtl_raw == expected_normal)
print("Matches Hypothesis B (reversed)?", actual_rtl_raw == expected_reversed)

Matches Hypothesis A (normal)? False
Matches Hypothesis B (reversed)? False


In [13]:
for ch in range(6):  # conv0 has 6 output channels
    weight_normal_int = round(float(fused_weights[0, 0, 0, ch]) * (2**Nfrac_weight))
    weight_reversed_int = round(float(fused_weights[2, 2, 0, ch]) * (2**Nfrac_weight))
    bias_int = round(float(fused_bias[ch]) * (2**Nfrac_weight))

    product_normal = (pixel_val_int * weight_normal_int) >> Nfrac_pixel
    product_reversed = (pixel_val_int * weight_reversed_int) >> Nfrac_pixel

    expected_normal = product_normal + bias_int
    expected_reversed = product_reversed + bias_int

    print(f"ch={ch}: hyp_A={expected_normal}, hyp_B={expected_reversed}, "
          f"post-ReLU A={max(0,expected_normal)}, post-ReLU B={max(0,expected_reversed)}, "
          f"distinguishing? {(expected_normal>0) != (expected_reversed>0)}")

ch=0: hyp_A=4, hyp_B=-12, post-ReLU A=4, post-ReLU B=0, distinguishing? True
ch=1: hyp_A=-7, hyp_B=-20, post-ReLU A=0, post-ReLU B=0, distinguishing? False
ch=2: hyp_A=29, hyp_B=39, post-ReLU A=29, post-ReLU B=39, distinguishing? False
ch=3: hyp_A=-12, hyp_B=-17, post-ReLU A=0, post-ReLU B=0, distinguishing? False
ch=4: hyp_A=-22, hyp_B=-11, post-ReLU A=0, post-ReLU B=0, distinguishing? False
ch=5: hyp_A=-5, hyp_B=2, post-ReLU A=0, post-ReLU B=2, distinguishing? True


In [14]:
for ch in [1, 2, 3, 4]:
    actual = int(rtl_conv0_raw[0, ch])
    print(f"ch={ch}: actual RTL = {actual}")

ch=1: actual RTL = 17
ch=2: actual RTL = 23
ch=3: actual RTL = 0
ch=4: actual RTL = 20


In [15]:
layer1 = model.get_layer("q_conv2d_batchnorm_1")
fused_weights_1, fused_bias_1 = layer1.get_folded_weights()
print("fused_weights_1 shape:", fused_weights_1.shape)  # expect (3, 3, 6, 8)

# raw pool0 window at conv1's output position (row=4, col=4), in RAW INTEGER form
pool0_raw = np.loadtxt("/home/aya/HLS4ML_VS_MANUAL/src/hdl/RHEED_Gaussian/python/round_up_traces/rtl_2_pool0.csv", delimiter=',')  # shape (121, 6), raw ints
pool0_raw_2d = pool0_raw  # already (121, 6)

def get_raw_window(pool_raw, row, col, width=11):
    idxs = [(row+dr)*width + (col+dc) for dr in range(3) for dc in range(3)]
    return pool_raw[idxs]  # shape (9, 6), raw integers

window_raw = get_raw_window(pool0_raw_2d, 4, 4)
print("raw window (9 positions x 6 channels):\n", window_raw)

fused_weights_1 shape: (3, 3, 6, 8)
raw window (9 positions x 6 channels):
 [[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 7. 16.  0. 25.  0.  0.]
 [28. 20. 29.  0.  5.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0. 27.  0.  0.  0.]
 [ 0. 17. 23.  0. 20.  0.]]


In [16]:
Nfrac_weight1 = 5   # conv1's weight Nfrac
Nfrac_input1 = 6    # pool0's output Nfrac (confirmed earlier)
out_ch = 3          # pick a channel with a large known discrepancy

total = 0
for pos in range(9):
    h, w = pos // 3, pos % 3
    for in_ch in range(6):
        weight_val = float(fused_weights_1[h, w, in_ch, out_ch])
        weight_int = round(weight_val * (2**Nfrac_weight1))
        pixel_int = int(window_raw[pos, in_ch])
        total += (pixel_int * weight_int) >> Nfrac_input1

bias_int = round(float(fused_bias_1[out_ch]) * (2**Nfrac_weight1))
expected_raw = total + bias_int
print("expected raw output (before ReLU):", expected_raw)
print("expected post-ReLU:", max(0, expected_raw))

expected raw output (before ReLU): -13
expected post-ReLU: 0


In [17]:
conv1_raw = np.loadtxt("/home/aya/HLS4ML_VS_MANUAL/src/hdl/RHEED_Gaussian/python/round_up_traces/rtl_2_conv1.csv", delimiter=',')  # shape (81, 8), raw ints
actual_raw = int(conv1_raw[4*9 + 4, out_ch])  # position (row=4,col=4) -> flat index 4*9+4=40, channel 3
print("actual RTL raw value:", actual_raw)
print("match?", actual_raw == max(0, expected_raw))

actual RTL raw value: 0
match? True


In [18]:
running_total = 0
for pos in range(9):
    h, w = pos // 3, pos % 3
    pos_contribution = 0
    for in_ch in range(6):
        weight_val = float(fused_weights_1[h, w, in_ch, out_ch])
        weight_int = round(weight_val * (2**Nfrac_weight1))
        pixel_int = int(window_raw[pos, in_ch])
        term = (pixel_int * weight_int) >> Nfrac_input1
        pos_contribution += term
    running_total += pos_contribution
    print(f"pos={pos} (h={h},w={w}): contribution={pos_contribution}, running_total={running_total}")

print(f"+ bias={bias_int} -> final={running_total + bias_int}")

pos=0 (h=0,w=0): contribution=0, running_total=0
pos=1 (h=0,w=1): contribution=0, running_total=0
pos=2 (h=0,w=2): contribution=0, running_total=0
pos=3 (h=1,w=0): contribution=0, running_total=0
pos=4 (h=1,w=1): contribution=1, running_total=1
pos=5 (h=1,w=2): contribution=-8, running_total=-7
pos=6 (h=2,w=0): contribution=0, running_total=-7
pos=7 (h=2,w=1): contribution=-3, running_total=-10
pos=8 (h=2,w=2): contribution=0, running_total=-10
+ bias=-3 -> final=-13


In [19]:
running_total_reversed_ch = 0
for pos in range(9):
    h, w = pos // 3, pos % 3
    pos_contribution = 0
    for in_ch in range(6):
        # try REVERSED channel indexing: pool0's channel `in_ch` pairs with weight's channel `5-in_ch`
        weight_val = float(fused_weights_1[h, w, 5 - in_ch, out_ch])
        weight_int = round(weight_val * (2**Nfrac_weight1))
        pixel_int = int(window_raw[pos, in_ch])
        term = (pixel_int * weight_int) >> Nfrac_input1
        pos_contribution += term
    running_total_reversed_ch += pos_contribution

expected_reversed_ch = running_total_reversed_ch + bias_int
print("expected (reversed channel order):", expected_reversed_ch)
print("expected post-ReLU:", max(0, expected_reversed_ch))
print("matches actual RTL (15)?", max(0, expected_reversed_ch) == 15)

expected (reversed channel order): 1
expected post-ReLU: 1
matches actual RTL (15)? False


In [20]:
import itertools

def compute_with_channel_map(channel_map):
    total = 0
    for pos in range(9):
        h, w = pos // 3, pos % 3
        for in_ch in range(6):
            weight_val = float(fused_weights_1[h, w, channel_map[in_ch], out_ch])
            weight_int = round(weight_val * (2**Nfrac_weight1))
            pixel_int = int(window_raw[pos, in_ch])
            total += (pixel_int * weight_int) >> Nfrac_input1
    return total + bias_int

# test a few plausible remappings
identity = list(range(6))
reversed_map = list(range(5, -1, -1))
print("identity:", max(0, compute_with_channel_map(identity)))
print("reversed:", max(0, compute_with_channel_map(reversed_map)))

identity: 0
reversed: 1


In [21]:
from itertools import permutations

def compute_with_channel_map(channel_map):
    total = 0
    for pos in range(9):
        h, w = pos // 3, pos % 3
        for in_ch in range(6):
            weight_val = float(fused_weights_1[h, w, channel_map[in_ch], out_ch])
            weight_int = round(weight_val * (2**Nfrac_weight1))
            pixel_int = int(window_raw[pos, in_ch])
            total += (pixel_int * weight_int) >> Nfrac_input1
    return max(0, total + bias_int)  # post-ReLU

matches = []
for perm in permutations(range(6)):
    result = compute_with_channel_map(list(perm))
    if result == 15:
        matches.append(perm)

print(f"Found {len(matches)} permutation(s) matching actual RTL value (15):")
for m in matches:
    print(m)

Found 0 permutation(s) matching actual RTL value (15):


In [25]:

row, col, out_ch = 40 // 9, 40 % 9, 5   # row=4, col=4, channel 5

pool0_raw = np.loadtxt("/home/aya/HLS4ML_VS_MANUAL/src/hdl/RHEED_Gaussian/python/round_up_traces/rtl_2_pool0.csv", delimiter=',')

def get_raw_window(pool_raw, row, col, width=11):
    idxs = [(row+dr)*width + (col+dc) for dr in range(3) for dc in range(3)]
    return pool_raw[idxs]

window_raw = get_raw_window(pool0_raw, row, col)

Nfrac_weight1 = 5
Nfrac_input1 = 6

running_total = 0
for pos in range(9):
    h, w = pos // 3, pos % 3
    pos_contribution = 0
    for in_ch in range(6):
        weight_val = float(fused_weights_1[h, w, in_ch, out_ch])
        weight_int = round(weight_val * (2**Nfrac_weight1))
        pixel_int = int(window_raw[pos, in_ch])
        term = (pixel_int * weight_int) >> Nfrac_input1
        pos_contribution += term
    running_total += pos_contribution
    print(f"pos={pos} (h={h},w={w}): contribution={pos_contribution}, running_total={running_total}")

bias_int = round(float(fused_bias_1[out_ch]) * (2**Nfrac_weight1))
expected_raw = running_total + bias_int
print(f"+ bias={bias_int} -> expected final={expected_raw}, post-ReLU={max(0,expected_raw)}")

conv1_raw = np.loadtxt("/home/aya/HLS4ML_VS_MANUAL/src/hdl/RHEED_Gaussian/python/round_up_traces/rtl_2_conv1.csv", delimiter=',')
actual_raw = int(conv1_raw[row*9 + col, out_ch])
print("actual RTL raw value:", actual_raw)

pos=0 (h=0,w=0): contribution=0, running_total=0
pos=1 (h=0,w=1): contribution=0, running_total=0
pos=2 (h=0,w=2): contribution=0, running_total=0
pos=3 (h=1,w=0): contribution=0, running_total=0
pos=4 (h=1,w=1): contribution=-3, running_total=-3
pos=5 (h=1,w=2): contribution=-2, running_total=-5
pos=6 (h=2,w=0): contribution=0, running_total=-5
pos=7 (h=2,w=1): contribution=0, running_total=-5
pos=8 (h=2,w=2): contribution=-3, running_total=-8
+ bias=2 -> expected final=-6, post-ReLU=0
actual RTL raw value: 0


In [26]:
row, col, out_ch = 40 // 9, 40 % 9, 5

pool0_raw = np.loadtxt("/home/aya/HLS4ML_VS_MANUAL/src/hdl/RHEED_Gaussian/python/round_up_traces/rtl_2_pool0.csv", delimiter=',')

def get_raw_window(pool_raw, row, col, width=11):
    idxs = [(row+dr)*width + (col+dc) for dr in range(3) for dc in range(3)]
    return pool_raw[idxs]

window_raw = get_raw_window(pool0_raw, row, col)

pool0_hls_raw = np.loadtxt("/home/aya/HLS4ML_VS_MANUAL/src/hdl/RHEED_Gaussian/python/traces/hls4ml_2_max_pooling2d.csv", delimiter=',').reshape(-1, 6)
window_hls = pool0_hls_raw[[(row+dr)*11 + (col+dc) for dr in range(3) for dc in range(3)]]

print("RTL window (raw ints):\n", window_raw)
print("hls4ml window (decimal):\n", window_hls)
print("hls4ml window as raw ints (nfrac=6):\n", np.round(window_hls * 64).astype(int))

RTL window (raw ints):
 [[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 7. 16.  0. 25.  0.  0.]
 [28. 20. 29.  0.  5.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0. 27.  0.  0.  0.]
 [ 0. 17. 23.  0. 20.  0.]]
hls4ml window (decimal):
 [[0.      0.      0.      0.      0.      0.     ]
 [0.      0.      0.      0.      0.      0.     ]
 [0.      0.      0.      0.      0.      0.     ]
 [0.      0.      0.      0.      0.      0.     ]
 [0.09375 0.25    0.      0.375   0.      0.     ]
 [0.4375  0.3125  0.4375  0.      0.09375 0.     ]
 [0.      0.      0.      0.      0.      0.     ]
 [0.      0.      0.40625 0.      0.      0.     ]
 [0.      0.25    0.34375 0.      0.3125  0.     ]]
hls4ml window as raw ints (nfrac=6):
 [[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 6 16  0 24  0  0]
 [28 20 28  0  6  0]
 [ 0  0  0  0  0  0]
 [ 0  0 26  0  0  0]
 [ 0 16 22  0 20  0]]
